# .github/workflows/build-and-release.yml
name: 📦 Build & Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: 🔨 Build on Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          docker run --rm -i \
            -v $PWD:/project \
            -v ~/.cache/electron:/root/.cache/electron \
            -v ~/.cache/electron-builder:/root/.cache/electron-builder \
            electronuserland/builder:wine \
            bash -lc "npm ci && npm run dist:linux"

      - name: 🔨 Build on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: npm run dist:win

      - name: 🔨 Build on macOS
        if: runner.os == 'macOS'
        shell: bash
        run: npm run dist:mac

      - name: 📂 Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: dist/**
